#version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      #- "8000:80" #Test
      - "3005:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TINYMCE_KEY=${TINYMCE_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORTA=${SMTP_PORTA}
      - SMTP_USUARIO=${SMTP_USUARIO}
      - SMTP_SENHA=${SMTP_SENHA}
      - EMAIL_ENVIO=${EMAIL_ENVIO}
      - NOME_REMETENTE=${NOME_REMETENTE}