version: '3.8'

services:
  app:
    build: .
    container_name: sispmpi_app
    ports:
      - "3004:80"
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
